### ISSUE TITLE
📚 Documentation: Mistake in code snippets in getting started guide

### ISSUE THREAD

**Issue by FloLan1** [appwrite/sdk-for-python#62] opened 2023-06-15 20:29 UTC
### 💭 Description

The code snippet for creating a user in the getting started guide throws an error due to an invalide phone number. 
This:
```python
result = users.create('[USER_ID]', 'email@example.com', 'password')
``` 
should be changed to:
```python
result = users.create(ID.unique(), email = 'email1@example.com', phone = '+123456789', password = 'password', name = 'user1')
``` 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-06-19 13:56
Hey there,

Thanks for reaching out. We appreciate you bringing this to our attention. Rest assured, we're aware of the issue, and we'll make sure to update it with the correct syntax. In the meantime, we recommend checking out our documentation, as it has been updated with the accurate examples you need. You can find them here: https://appwrite.io/docs/getting-started-for-server#makeRequest

If you have any further questions or need any assistance, feel free to ask

**Comment by stnguyen90** [comment] 2023-09-22 17:21
It seems like [this](https://github.com/appwrite/appwrite/blob/master/docs/sdks/python/GETTING_STARTED.md) is the file that needs to be updated to fix this.

**Comment by aniketh-varma** [comment] 2023-10-01 18:58
Hi @Haimantika, I would like to work on this issue, if it is up for grabs.

**Comment by Haimantika** [comment] 2023-10-02 09:10
> Hi @Haimantika, I would like to work on this issue, if it is up for grabs.

Hi @aniketh-varma have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by GuptaPratik02** [comment] 2023-10-03 15:14
Hi @Haimantika , if the previous contributor is unresponsive, I would like to work on this issue then please assign it to me later on.
Thanks!

**Comment by aniketh-varma** [comment] 2023-10-03 19:44
Hi @Haimantika, just to confirm, if [this](https://github.com/appwrite/appwrite/blob/master/docs/sdks/python/GETTING_STARTED.md) is the file to be updated. Then the PR I would create would be for the `appwrite` repo and not the current `sdk-for-python` repo. Am I correct on this?

**Comment by GuptaPratik02** [comment] 2023-10-06 07:22
Hi @Haimantika, there is NO update/changes seen from previous assignee in this issue since 4-5 days?
Can you assign it to me? 
I will be quick and make a PR soon!

**Comment by Haimantika** [comment] 2023-10-06 07:29
> Hi @Haimantika, there is NO update/changes seen from previous assignee in this issue since 4-5 days?
> Can you assign it to me?
> I will be quick and make a PR soon!

Yes! @aniketh-varma we are reassigning the issue to the next person due to inactivity from your end. @GuptaPratik02 the issue is yours now

**Comment by GuptaPratik02** [comment] 2023-10-06 07:39
Thanks @Haimantika, will update you by today!

**Comment by GuptaPratik02** [comment] 2023-10-06 13:09
Hi @Haimantika,
I have checked the doc files that needs to be updated, I raised 2 PRs and made changes in 2 repositories doc file.
1. First change I made in this repository's [README file](https://github.com/GuptaPratik02/sdk-for-python/blob/update-readme-file/README.md)  **-**  [Pull request 1](https://github.com/appwrite/sdk-for-python/pull/74)
2. Second change I made in appwrite repository's [Getting_Started file](https://github.com/GuptaPratik02/appwrite/blob/doc-sdks-python-update-getting-started-guide/docs/sdks/python/GETTING_STARTED.md)  **-**  [Pull request 2](https://github.com/appwrite/appwrite/pull/6826)

Kindly check and review my PR.
Thank you!

**Comment by aniketh-varma** [comment] 2023-10-06 19:49
@Haimantika I was waiting for your reply on the query I had asked, the confusion being an issue for the `appwrite` repository was raised in this `sdk-for-python` repository. I have been participating in Hacktoberfests since 2019 and haven't seen such practices of reassignments in other projects to which I have contributed. This puts pressure on the assignee and defeats the entire purpose of Hacktoberfest, which is to encourage more contributions. Being a part of the contributor team of Appwrite since 2020 (the first time Appwrite had taken part in Hacktoberfest), I did not expect this, and reassigning issues without any confirmation from the current assignee is very wrong. I have been assigned many issues in other projects and I am given ample time to solve the issues without any 'deadline' pressure :)

**Comment by prithvi2k2** [comment] 2023-10-08 00:45
> @Haimantika I was waiting for your reply on the query I had asked, the confusion being an issue for the `appwrite` repository was raised in this `sdk-for-python` repository. I have been participating in Hacktoberfests since 2019 and haven't seen such practices of reassignments in other projects to which I have contributed. This puts pressure on the assignee and defeats the entire purpose of Hacktoberfest, which is to encourage more contributions. Being a part of the contributor team of Appwrite since 2020 (the first time Appwrite had taken part in Hacktoberfest), I did not expect this, and reassigning issues without any confirmation from the current assignee is very wrong. I have been assigned many issues in other projects and I am given ample time to solve the issues without any 'deadline' pressure :)

With that much of experience, you should have read the appwrite rules on contributing during hacktoberfest brother... they clearly stated 3 days of inactivity could roll over issue to others

**Comment by aniketh-varma** [comment] 2023-10-08 07:13
> > @Haimantika I was waiting for your reply on the query I had asked, the confusion being an issue for the `appwrite` repository was raised in this `sdk-for-python` repository. I have been participating in Hacktoberfests since 2019 and haven't seen such practices of reassignments in other projects to which I have contributed. This puts pressure on the assignee and defeats the entire purpose of Hacktoberfest, which is to encourage more contributions. Being a part of the contributor team of Appwrite since 2020 (the first time Appwrite had taken part in Hacktoberfest), I did not expect this, and reassigning issues without any confirmation from the current assignee is very wrong. I have been assigned many issues in other projects and I am given ample time to solve the issues without any 'deadline' pressure :)
> 
> With that much of experience, you should have read the appwrite rules on contributing during hacktoberfest brother... they clearly stated 3 days of inactivity could roll over issue to others. Atleast you could've opened a draft PR if it was taking time

Thanks for the advice man. I appreciate Appwrite for abiding by the rules, but a simple confirmation before re-assigning the issue would be more courteous to the current assignee and would confirm the inactivity on the issue.
I don't know if you've contributed to other projects, but the assignees are not pressurised to complete the issues within specific deadlines, threatening to roll over the issue to somebody else without confirming. For this issue, a draft PR would be the equivalent of a normal PR :)

**Comment by GuptaPratik02** [comment] 2023-10-09 08:17
> Hi @Haimantika, I have checked the doc files that needs to be updated, I raised 2 PRs and made changes in 2 repositories doc file.
> 
> 1. First change I made in this repository's [README file](https://github.com/GuptaPratik02/sdk-for-python/blob/update-readme-file/README.md)  **-**  [Pull request 1](https://github.com/appwrite/sdk-for-python/pull/74)
> 2. Second change I made in appwrite repository's [Getting_Started file](https://github.com/GuptaPratik02/appwrite/blob/doc-sdks-python-update-getting-started-guide/docs/sdks/python/GETTING_STARTED.md)  **-**  [Pull request 2](https://github.com/appwrite/appwrite/pull/6826)
> 
> Kindly check and review my PR. Thank you!

Hi @Haimantika, can you acknowledge once that pull request I made is assigned to a maintainer to review?

**Comment by Haimantika** [comment] 2023-10-11 12:08
> @Haimantika I was waiting for your reply on the query I had asked, the confusion being an issue for the `appwrite` repository was raised in this `sdk-for-python` repository. I have been participating in Hacktoberfests since 2019 and haven't seen such practices of reassignments in other projects to which I have contributed. This puts pressure on the assignee and defeats the entire purpose of Hacktoberfest, which is to encourage more contributions. Being a part of the contributor team of Appwrite since 2020 (the first time Appwrite had taken part in Hacktoberfest), I did not expect this, and reassigning issues without any confirmation from the current assignee is very wrong. I have been assigned many issues in other projects and I am given ample time to solve the issues without any 'deadline' pressure :)

Hi @aniketh-varma apologies if you feel this way, that wasn't the intention at all. We wanted to give a fair chance to everyone to contribute. Since in the past we have had cases where people didn't work on an issue and others didn't get a chance to work on it either. 
I did react a thumbs-up on your query, I perhaps should have also dropped a message, and I apologise for that. We didn't want to put a deadline, we just wanted an update every 3 days, once again, apologies for making you feel this way.  :)

**Comment by akash47angadi** [comment] 2023-10-15 04:49
@Haimantika I would like to work on this. Can you assign it to me?

**Comment by aniketh-varma** [comment] 2023-10-24 10:54
> > @Haimantika I was waiting for your reply on the query I had asked, the confusion being an issue for the `appwrite` repository was raised in this `sdk-for-python` repository. I have been participating in Hacktoberfests since 2019 and haven't seen such practices of reassignments in other projects to which I have contributed. This puts pressure on the assignee and defeats the entire purpose of Hacktoberfest, which is to encourage more contributions. Being a part of the contributor team of Appwrite since 2020 (the first time Appwrite had taken part in Hacktoberfest), I did not expect this, and reassigning issues without any confirmation from the current assignee is very wrong. I have been assigned many issues in other projects and I am given ample time to solve the issues without any 'deadline' pressure :)
> 
> Hi @aniketh-varma apologies if you feel this way, that wasn't the intention at all. We wanted to give a fair chance to everyone to contribute. Since in the past we have had cases where people didn't work on an issue and others didn't get a chance to work on it either. I did react a thumbs-up on your query, I perhaps should have also dropped a message, and I apologise for that. We didn't want to put a deadline, we just wanted an update every 3 days. :)

Hey @Haimantika, I completely understand, that tracking the repos' issues, that too during the Hacktoberfest is a tedious task, and I really appreciate that Appwrite is abiding by the rules. I was just not happy about the reassignment of the issue without any confirmation from my end. There is no need for an apology, you are doing your work, I would just want to suggest, maybe a comment confirming the activity on an inactive issue may be a better alternative than just re-assigning. Thanks! 😄

**Closed** 2024-05-07 22:12 UTC
Labels: bug, good first issue, hacktoberfest
